### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by go-hacks** [alimpfard/megafs-fuse#1]
Doesn't work. All I get is this at runtime.

/usr/include/c++/11.1.0/debug/vector:438:
In function:
    std::__debug::vector<_Tp, _Allocator>::reference 
    std::__debug::vector<_Tp, 
    _Allocator>::operator[](std::__debug::vector<_Tp, 
    _Allocator>::size_type) [with _Tp = MegaFuseModel*; _Allocator = 
    std::allocator<MegaFuseModel*>; std::__debug::vector<_Tp, 
    _Allocator>::reference = MegaFuseModel*&; std::__debug::vector<_Tp, 
    _Allocator>::size_type = long unsigned int]

Error: attempt to subscript container with out-of-bounds index 0, but 
container only holds 0 elements.

Objects involved in the operation:
    sequence "this" @ 0x0x7ffc58b23740 {
      type = std::__debug::vector<MegaFuseModel*, std::allocator<MegaFuseModel*> >;
    }
Aborted

**Comment by alimpfard** [comment]
Not entirely sure where this comes from (a stack trace would be nice), I suspect a bad config?
I'm not sure if the old sdk that this uses actually works these days, I remember mega changing their API recently

**Comment by go-hacks** [comment]
I used your config example but I used the same account in both sections just to try it.. IDK if that would cause the issue. I'd be happy to provide a trace if you tell me how :) I'm not exactly a c++ guy :)
I think you're right on the API changing because every megafs type utility I can find just blows up when I try to run it and they're all several years old. Thinking of trying to make my own in Go but I'd have to learn the SDK I think and fuse of course.

**Comment by alimpfard** [comment]
Using the same account several times should be fine...I think...
you can generate a trace by running it under gdb:
```
$ gdb ./MegaFuse
```
`run` in gdb will run the program, and you can get a backtrace after it crashes with `bt`.

**Comment by go-hacks** [comment]
I'm just realizing this appkey is something I had to get. I have one now but it didn't make a difference. Here's the trace...I replaced user and keys with XXXXX.

(gdb) run
Starting program: /home/sm177y/megafs-fuse/MegaFuse 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
variable USERNAME has value XXXXX
variable PASSWORD has value XXXXX
variable LOADBALANCE_QUOTA has value 1024000
variable LOADBALANCE_PRIORITY has value 2
variable USERNAME has value XXXXX
variable PASSWORD has value XXXXX
variable LOADBALANCE_QUOTA has value 1024000
variable APPKEY has value XXXXX
variable MOUNTPOINT has value /mnt/mega
variable CACHEPATH has value /tmp
[New Thread 0x7ffff602c640 (LWP 10057)]
Start of event_loop
[New Thread 0x7ffff582b640 (LWP 10058)]
MegaFS::MegaFuse. Constructor finished.
Processing user XXXXX (idx 0)...
/usr/include/c++/11.1.0/debug/vector:438:
In function:
    std::__debug::vector<_Tp, _Allocator>::reference 
    std::__debug::vector<_Tp, 
    _Allocator>::operator[](std::__debug::vector<_Tp, 
    _Allocator>::size_type) [with _Tp = MegaFuseModel*; _Allocator = 
    std::allocator<MegaFuseModel*>; std::__debug::vector<_Tp, 
    _Allocator>::reference = MegaFuseModel*&; std::__debug::vector<_Tp, 
    _Allocator>::size_type = long unsigned int]

Error: attempt to subscript container with out-of-bounds index 0, but 
container only holds 0 elements.

Objects involved in the operation:
    sequence "this" @ 0x0x7fffffffe200 {
      type = std::__debug::vector<MegaFuseModel*, std::allocator<MegaFuseModel*> >;
    }

Thread 3 "MegaFuse" received signal SIGABRT, Aborted.
[Switching to Thread 0x7ffff582b640 (LWP 10058)]
0x00007ffff7207ef5 in raise () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff7207ef5 in raise () from /usr/lib/libc.so.6
#1  0x00007ffff71f1862 in abort () from /usr/lib/libc.so.6
#2  0x00007ffff75b721e in __gnu_debug::_Error_formatter::_M_error (this=<optimized out>)
    at /build/gcc/src/gcc/libstdc++-v3/src/c++11/debug.cc:1123
#3  0x000055555559cf3e in std::__debug::vector<MegaFuseModel*, std::allocator<MegaFuseModel*> >::operator[] (this=0x7fffffffe200, __n=0)
    at /usr/include/c++/11.1.0/debug/vector:438
#4  0x0000555555593317 in MegaFuse::findCorrespondingMaidEntry (this=0x7fffffffe170, path=0x55555566ee45 "/.megafuse_symlink")
    at src/MegaFuse.cpp:56
#5  0x0000555555597510 in MegaFuse::serializeSymlink (this=0x7fffffffe170) at src/MegaFuse.cpp:669
#6  0x0000555555593a55 in MegaFuse::maintenance (that=0x7fffffffe170) at src/MegaFuse.cpp:99
#7  0x00005555555b3531 in std::__invoke_impl<void, void (*)(MegaFuse*), MegaFuse*> (
    __f=@0x55555571d2b0: 0x555555593a20 <MegaFuse::maintenance(MegaFuse*)>) at /usr/include/c++/11.1.0/bits/invoke.h:61
#8  0x00005555555b33ba in std::__invoke<void (*)(MegaFuse*), MegaFuse*> (
    __fn=@0x55555571d2b0: 0x555555593a20 <MegaFuse::maintenance(MegaFuse*)>) at /usr/include/c++/11.1.0/bits/invoke.h:96
#9  0x00005555555b31ce in std::thread::_Invoker<std::tuple<void (*)(MegaFuse*), MegaFuse*> >::_M_invoke<0ul, 1ul> (this=0x55555571d2a8)
    at /usr/include/c++/11.1.0/bits/std_thread.h:253
#10 0x00005555555b3105 in std::thread::_Invoker<std::tuple<void (*)(MegaFuse*), MegaFuse*> >::operator() (this=0x55555571d2a8)
    at /usr/include/c++/11.1.0/bits/std_thread.h:260
#11 0x00005555555b305b in std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (*)(MegaFuse*), MegaFuse*> > >::_M_run (
    this=0x55555571d2a0) at /usr/include/c++/11.1.0/bits/std_thread.h:211
#12 0x00007ffff75ee3c4 in std::execute_native_thread_routine (__p=0x55555571d2a0) at /build/gcc/src/gcc/libstdc++-v3/src/c++11/thread.cc:82
#13 0x00007ffff73a1299 in start_thread () from /usr/lib/libpthread.so.0
#14 0x00007ffff72ca053 in clone () from /usr/lib/libc.so.6
(gdb)

**Comment by alimpfard** [comment]
Looks like the "maintenance" thread kicks in before the login is complete, and a function in there doesn't have a check against that.
adding the check should fix _that_ specific issue.

```diff
diff --git a/src/MegaFuse.cpp b/src/MegaFuse.cpp
index ced3e4d..083db9a 100644
--- a/src/MegaFuse.cpp
+++ b/src/MegaFuse.cpp
@@ -656,6 +656,8 @@ int MegaFuse::readlink(const char *path, char *buf, size_t bufsiz) {
 }
 // TODO: Make it on binary mode like serializeXattr
 int MegaFuse::serializeSymlink() {
+  if (!maidcontroller.models.size())
+    return 1;
   std::string sep = ";";
   std::string tmpbuf;
   std::stringstream line;
```

**Comment by go-hacks** [comment]
Well that patch fixed the above issue. It's still not working though...

It dies with 
waiting for login...
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
FATAL: Request failed (Expired), exiting

My credentials are definitely right. I tried my password with and without "" as it contains several symbols. Wasn't sure if escape characters would cause problems in the conf.

**Comment by alimpfard** [comment]
Yeah I think that's about the sdk issue.
I don't think this will work then

**Comment by go-hacks** [comment]
Bummer...I appreciate the effort :) I really just want to be able to mount megas like this so I can create file level raid across them with ext4 container files :)

All the projects I can find like this on github tho don't work for various reasons. At least yours didn't lock up my computer like one of the others I tried XD

Maybe some other day...
